spring.application.name=coreservices

#Server Port
server.port=${PORT:8020}

#MongoDB Configuration
spring.mongodb.uri=${MONGODB_URI:mongodb+srv://test:admin123@cluster0.hxyc73f.mongodb.net/Accessible_Knowledge_System_1?appName=Cluster0m}
spring.mongodb.database=Accessible_Knowledge_System

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
